"""add anomaly_note to post_ai_annotations

Revision ID: b1df913e4d40
Revises: 48d02220d7aa
Create Date: 2026-09-12 19:03:50.851954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1df913e4d40'
down_revision: Union[str, Sequence[str], None] = '48d02220d7aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_ai_annotations', sa.Column('anomaly_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_ai_annotations', 'anomaly_note')
    # ### end Alembic commands ###
